### ISSUE TITLE
command idea's

### ISSUE THREAD

**Issue by YasinK2003** [LUKAY207/UltraEssentials#1]
/tpto teleports to the block you are lookin at
/heal
/feed
/skin (takes a skin from the web)
/nick, /unnick
/alias (checks for possibile alt accounts using ip adresses)

**Comment by LUKAY207** [comment]
Thanks, will be added to my To Do's for this Plugin.

**Comment by LUKAY207** [comment]
Added /nick, /unick, /account (/alias), /heal, /feed, /tpto and /skin will not be added yet.
